### ISSUE TITLE
TEST SPARK: Discover Payload CIDs stored in Filecoin deals

### ISSUE THREAD

**Issue by bajtos** [filecoin-project/roadmap#15]
Description: Rework SPARK orchestration layer to dynamically sample Filecoin storage deals to discover PieceCIDs/DealProposalCIDs and then query IPNI to get PayloadCIDs.

ETA: 2023-12-15
Maintainer: @bajtos

```[tasklist]
### Milestones
- [ ] Use Datacap API to obtain the list of client IDs notarised for LDN FIL+ deals
- [ ] Pick a random FIL+ LDN deal from StorageMarketActor on-chain state
- [ ] Ask IPNI to give us a random PayloadCID stored in that deal
- [ ] https://github.com/filecoin-station/roadmap/issues/43
- [ ] https://github.com/filecoin-station/spark/issues/12
```

Known dependencies:
- IPNI reverse index API

View this [starmap](https://starmap.site/) at: https://starmap.site/roadmap/github.com/filecoin-project/roadmap/issues/15
