### ISSUE TITLE
Satellite in Mars with most important Humanity Data

### ISSUE THREAD

**Issue by ainhoa-a** [filecoin-project/roadmap#16]
Description: Most important humanity data is no longer safe in Earth, we need to expand to other horizons for better redundancy

ETA: 2024-01-01
Maintainer: Ainhoa Aldave

```[tasklist]
### Milestones
- [ ] Build a rocket + satellite
- [ ] Test a rocket  + satellite
- [ ] select Astronaut
- [ ] Train astronaut 
- [ ] Select data to be stored in mars
- [ ] Conquer mars
- [ ] Party 
```

Known dependencies:
- Filecoin retrievals

View this [starmap](https://starmap.site/) at: <link>
