### ISSUE TITLE
Granite

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/roadmap#17]
Description: The Granite effort aims to bring fast finality to Filecoin

See here for more: https://research.protocol.ai/talks/janus-and-granite/

ETA: 2024-02-22
Maintainer: Nina

```[tasklist]
### Milestones
- [ ] Finalize Granite design
- [ ] Design integration of Granite into Filecoin
- [ ] Implement and test the Granite module
- [ ] Run a testnet using Granite
- [ ] Write a FIP for Granite
- [ ] Ship Granite in a network upgrade
```

Known dependencies:
- nv22

View this [starmap](https://starmap.site/) at: https://starmap.site/roadmap/github.com/filecoin-project/roadmap/issues/17#view=detail
