### ISSUE TITLE
Ignite the Genesis Ark and make it settle first few planets orienting via the Starmap 

### ISSUE THREAD

**Issue by ArseniiPetrovich** [filecoin-project/roadmap#18]
Description: The design is ready already, now we need to write code, haha :) 

ETA: 2023-12-31
Maintainer: @ArseniiPetrovich

```[tasklist]
### Milestones
- [ ] M1 - Implement API server
- [ ] M2 - Implement DevOps scripts
- [ ] M3 - Implement UI
- [ ] M4 - Implement first version of Marketplace
- [ ] M5 - Allow customization of existing networks
```

Known dependencies:
- [IPC network functionality](https://github.com/filecoin-project/roadmap/issues/14)

View this [starmap](https://starmap.site/) at:
