### ISSUE TITLE
eat all the hot dogs in iceland 🌭🌭🌭

### ISSUE THREAD

**Issue by gruns** [filecoin-project/roadmap#24]
Description: iceland has some of the world's best hotdogs. but they don't eat themselves

ETA: 2023-09-28
Maintainer: ansgar, reid, patrick, and amean

```[tasklist]
### Milestones
- [ ] head to [Bæjarins beztu](https://maps.app.goo.gl/yJkwnG9cXa8Xfm7m9)
- [ ] procure hot dogs ‍🌭 
- [ ] consume hot dogs ‍🌭 
- [ ] recover and ship saturn 🪐 
```

Known dependencies:
- stomach compacity
- willingness to eat mystery meat

View this [starmap](https://starmap.site/) here: [‍🌭](https://starmap.site/roadmap/github.com/filecoin-project/roadmap/issues/24#view=simple)

**Comment by galen-mcandrew** [comment]
@dchoi27 gauntlet thrown
