### ISSUE TITLE
Define voting mechanism for "Ecosystem Partners" stakeholder in FIP0001v2

### ISSUE THREAD

**Issue by protocolin** [filecoin-project/roadmap#29]
Description: Ecosystem partners needs a defined voting mechanism in the next iteration of FIP0001 (improving the FIP process)

ETA: 2023-11-30
Maintainer: @protocolin 

```[tasklist]
### Milestones
- [ ] Define Ecosystem Parnters
- [ ] Define metrics on sizing their voting power
- [ ] Define practical voting mechanism
```

Known dependencies:
- FIP0001v2

View this [starmap](https://starmap.site/) at: <link>
