### ISSUE TITLE
Onboard my grandma's photo to Filecoin

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/roadmap#30]
Description: Onboard my grandma's photo to Filecoin

ETA: 2023-11-01
Maintainer: xinaxu

```[tasklist]
### Milestones
- [ ] Talk to my Grandma about Filecoin
- [ ] Ask for her agreement of onboarding her photos
- [ ] Convert her photos to CAR
- [ ] Find an SP and make deal
- [ ] Attemp Retrieval
```

Known dependencies:
- DeStor

View this [starmap](https://starmap.site/) at: <link>
