### ISSUE TITLE
Direct data onboarding

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/roadmap#32]
Description: Making the pipeline of putting data into Filecoin sectors more flexible.

ETA: 2024-02-22
Maintainer: Ozzy

```[tasklist]
### Milestones
- [ ] https://github.com/filecoin-project/builtin-actors/issues/1342
- [ ] https://github.com/filecoin-project/lotus/issues/11125
- [ ] build market interface FRC
```

Known dependencies:
- built in actors
- lotus
- lotus miner 
- many others 

View this [starmap](https://starmap.site/) at: https://starmap.site/roadmap/github.com/filecoin-project/roadmap/issues/32#view=simple
