### ISSUE TITLE
Enable Filecoin Native File System.

### ISSUE THREAD

**Issue by suykerbuyk** [filecoin-project/roadmap#37]
Description: 4x to 20x improvement in the performance of Sector random access performance.

ETA: 2023-12-01
Maintainer: John Suykerbuyk

```[tasklist]
### Milestones
- [ ] Consensus on proposal
- [ ] Demonstration of concept.
- [ ] Write a FIPS
- [ ] Test in Lotus
```

Known dependencies:
- <add here>
https://docs.google.com/presentation/d/1zTrhJH8FOQvCmY_s3zZN4ujGQzLQT3UJcR3dkTWmG1I/edit?usp=sharing
View this [starmap](https://starmap.site/) at: <link>
