### ISSUE TITLE
IPC Roadmap

### ISSUE THREAD

**Issue by mturilin** [filecoin-project/roadmap#40]
Description: This is full IPC roadmap 

ETA: 2024-06-01
Maintainer: 

```[tasklist]
### Milestones
- [ ] https://github.com/filecoin-project/roadmap/issues/27
- [ ] https://github.com/filecoin-project/roadmap/issues/22
- [ ] https://github.com/filecoin-project/roadmap/issues/14
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
