### ISSUE TITLE
Survive a Trump reelection

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/roadmap#42]
Description: <add here>

ETA: YYY-MM-DD
Maintainer: 

```[tasklist]
### Milestones
- [ ] <add here>
- [ ] Become a prepper
- [ ] Learn a lot about immigration
- [ ] Drink, and/or explore the depths of depression
- [ ] Read some Sartre
- [ ] Nucleate from US
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
