### ISSUE TITLE
Data Programmability / Compute (FVM, COD, actor endpoints, wasm)

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/roadmap#48]
Description: <add here>

ETA: 2024-12-01
Maintainer: 

```[tasklist]
### Milestones
- [ ] https://github.com/filecoin-project/fvm-pm/issues/719
- [ ] https://github.com/filecoin-project/fvm-pm/issues/825
- [ ] https://github.com/filecoin-project/fvm-pm/issues/816
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>

**Comment by DeveloperAlly** [comment]
#91 
#87
