### ISSUE TITLE
Community Growth (SPs, clients, devs, builders, token holders, etc)

### ISSUE THREAD

**Issue by Stefaan-V** [filecoin-project/roadmap#49]
Description: Root node 

ETA: 2023-09-27

Maintainer: 

```[tasklist]
### Milestones
- [ ] https://github.com/filecoin-project/roadmap/issues/53
- [ ] https://github.com/filecoin-project/roadmap/issues/67
- [ ] https://github.com/filecoin-project/roadmap/issues/60
- [ ] https://github.com/filecoin-project/roadmap/issues/58
- [ ] https://github.com/filecoin-project/FIPs/issues/836
- [ ] https://github.com/filecoin-project/roadmap/issues/78
- [ ] https://github.com/filecoin-project/roadmap/issues/71
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
