### ISSUE TITLE
get juan elected president

### ISSUE THREAD

**Issue by laudiacay** [filecoin-project/roadmap#5]
Description: president of the united states of america

ETA: 2024-11-05
Maintainer: Claudia Richoux

```[tasklist]
### Milestones
- [ ] purchase mail-in ballots
- [ ] mail them in
- [ ] executive order: ban jeff bezos
- [ ] executive order: regulate all non-CID data as munition
```

Known dependencies:
- executive orders epic

View this [starmap](https://starmap.site/) at: <link>
