### ISSUE TITLE
Security & Observability (critical system observability / decentralization / tooling / infra)

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/roadmap#55]
Description: <add here>

ETA: 2099-12-32
Maintainer: @Kubuxu

```[tasklist]
### Milestones
- [ ] https://github.com/ChainSafe/forest/issues/2789
- [ ] https://github.com/filecoin-project/roadmap/issues/68
- [ ] https://github.com/ChainSafe/forest/issues/3525
- [ ] https://github.com/filecoin-project/roadmap/issues/70
- [ ] https://github.com/filecoin-project/roadmap/issues/73
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
