### ISSUE TITLE
Network Scalability / L2s / Bridges

### ISSUE THREAD

**Issue by jsoares** [filecoin-project/roadmap#56]
Description: Subnets, fast finality, cross-net capabilities

ETA: 2024-12-31
Maintainer: @jsoares

```[tasklist]
### Milestones
- [ ] https://github.com/consensus-shipyard/consensuslab/issues/213
- [ ] https://github.com/filecoin-project/roadmap/issues/27
- [ ] https://github.com/filecoin-project/roadmap/issues/74
- [ ] https://github.com/filecoin-project/roadmap/issues/75
- [ ] https://github.com/filecoin-project/roadmap/issues/72
- [ ] Data availability chain (Sashimi)
- [ ] IPC Subnet configurability
- [ ] IPC Cross-net semantics
- [ ] IPC Observability
- [ ] IPC Zero-Knowledge support
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
