### ISSUE TITLE
3 Successful Enterprise Case Studies  

### ISSUE THREAD

**Issue by protocolin** [filecoin-project/roadmap#57]
Description: Develop 3 successful enterprise client case studies, with the help of SPs in the network

ETA: 2024-01-30
Maintainer: @protojen

```[tasklist]
### Milestones
- [ ] Seal to deliver market research on “legal hold” use case
- [ ] Seal to partner with DeStor on AI / Proof of Providence Use Case for Davos
- [ ] Steeldome to deliver analysis on “Ransomware” use case
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
