### ISSUE TITLE
Fast Finality for Filecoin GA

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/roadmap#66]
Description: Combination of projects that explore options for fast finality in Filecoin and features that are enabled at mainnet by providing faster finality (e.g. bridging).

ETA: 2024-12-31
Maintainer: @ranchalp

```[tasklist]
### Milestones
- [ ] Finalizer Component (Granite)
- [ ] Faster block time in mainnet 
- [ ] Proofs of finality (and of state transitions for power table) [bridging]
- [ ] Calculate faster finality given observed chain (for current mainchain)
```

Known dependencies:
- None (but other projects should depend on this).
