### ISSUE TITLE
IPC cross-net semantics

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/roadmap#69]
Description: IPC cross-net semantics

ETA: 2024-09-01
Maintainer: @adlrocha

```[tasklist]
### Milestones
- [ ] Cross-subnet ERC-20 transfers
- [ ] IPC support for custom native tokens in subnets
- [ ] Multi-subnet wallets (ability to interact with multiple IPC subnets without switching)
- [ ] Multi-subnet RPC endpoint protocol

```
