### ISSUE TITLE
Integrate IPNI service into demo.statechannels.org

### ISSUE THREAD

**Issue by geoknee** [filecoin-project/roadmap#7]
Description: Instead of having a particular storage provider baked in to the statechannels demo paid retrieval client, it should make  an IPNI query with the CID to find a provider and then connect to that provider in the usual way. 

ETA: 2023-12-25
Maintainer: @geoknee

```[tasklist]
### Milestones
- [ ] make an IPNI call in the demo to discover a storage provider
- [ ] augment the IPNI data structure response to be able to filter on whether a storage provider accepts nitro / state channel payments
- [ ] augment the IPNI data structure to return the cost of the file advertised by a given provider
```

Known dependencies:
-  IPNI data structure format

View this [starmap](https://starmap.site/) at: <link>
