### ISSUE TITLE
Update a webpage that showcases the Filecoin Ecosystem

### ISSUE THREAD

**Issue by protocolin** [filecoin-project/roadmap#78]
Description: Make it easy for community members to understand the applications building on Filecoin, and get a high level view of the developer & builder activity in the ecosystem (ie. an updated https://ecosystem.filecoin.io/)

ETA: 2024-03-31
Maintainer: @protocolin 

```[tasklist]
### Milestones
- [ ] Design a new website
- [ ] Source a way to collect inputs from community applications & builders to showcase their apps
- [ ] Launch the new website
- [ ] Promote it to the community & beyond to drive traffic to various applications and tooling
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
