### ISSUE TITLE
TVL of Filecoin and Filecoin derivatives grow to Top 3 in Web3

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/roadmap#79]
Description: <add here>

ETA: 2024-03-31
Maintainer: 

```[tasklist]
### Milestones
- [ ] DEX swaps on Filecoin (Sushi/Uniswap) with X amount of daily trading volume and Y amount of market liquidity
- [ ] Stablecoins on filecoin
- [ ] Borrowing/minting of stablecoins with Filecoin asset exceed X USD-equivalent
- [ ] Ways to add leverage for the ecosystem to express conviction
- [ ] Ways for ecosystem to express long-term bullish views
- [ ] Get major exchanges (Binance, etc.) to support f4 addresses

```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
