### ISSUE TITLE
Sound Protocol Economics 

### ISSUE THREAD

**Issue by vkalghatgi** [filecoin-project/roadmap#80]
Description: <Support a stable and healthy token economy. Minimize sources of volatility and optimize for sustainable growth>

ETA: 2024-08-30
Maintainer: @vkalghatgi 

```[tasklist]
### Milestones
- [ ] Upgrade Consensus Pledge Design
- [ ]  Protocol Based Lending and Liquidity Improvements
- [ ]  Improve Target lock design
- [ ]  Introduce dynamic control mechanisms and automatic stabilizers
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
