### ISSUE TITLE
Economic Tooling (DeFi, DEXs, stablecoins, token demand)

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/roadmap#84]
Description: <add here>

ETA: 2024-09-30
Maintainer: 

```[tasklist]
### Milestones
- [ ] https://github.com/filecoin-project/roadmap/issues/80
- [ ] https://github.com/filecoin-project/roadmap/issues/79
- [ ] https://github.com/filecoin-project/roadmap/issues/86
- [ ] https://github.com/filecoin-project/roadmap/issues/89
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
