### ISSUE TITLE
PoRep Optimizations

### ISSUE THREAD

**Issue by ninitrava** [filecoin-project/roadmap#85]
Description: Improve the PoRep design, find new PoRep to achieve better costs and storage capacity. 

ETA: 2025-03-01
Maintainer: @ninitrava

```[tasklist]
### Milestones
- [ ] Cheaper and faster PoRep
- [ ] Per storage medium PoRep’s to allow onboarding new storage media (e.g., tape)
- [ ] NI PoRep
- [ ] Better balance of winningPost and windowPost
- [ ] New CAR files to speedup snaps
```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
