### ISSUE TITLE
Find PMF in attracting significant capital

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/roadmap#86]
Description: <add here>

ETA: 2024-03-31
Maintainer: 

```[tasklist]
### Milestones
- [ ] Launch of market neutral products and protocols on Filecoin
- [ ] Launch of yield farming with Filecoin using other crypto assets
- [ ] Increasing token utility and interoperability with other ecosystems 

```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
