### ISSUE TITLE
Novel ways to pay for data and storage

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/roadmap#89]
Description: <add here>

ETA: 2024-09-30
Maintainer: 

```[tasklist]
### Milestones
- [ ] Pay for deals with ACH/Swift/credit card
- [ ] New storage seal pricing structures (e.g. reserve pricing for storage deals)
- [ ] Tokenizing datasets
- [ ] Retrieval pricing structures (depends on Proof of Access)
- [ ] Bounty style payment for deals

```

Known dependencies:
- <add here>

View this [starmap](https://starmap.site/) at: <link>
