### ISSUE TITLE
Ban saturn nodes for funzies 

### ISSUE THREAD

**Issue by AmeanAsad** [filecoin-project/roadmap#9]
Description: <add here>

ETA: 2023-10-24
Maintainer: @amean

```[tasklist]
### Milestones
- [ ] Ban the nodes on the network
- [ ] start my own node 
- [ ] profit
```

Known dependencies:
- Get Patrick's approval. 

View this [starmap](https://starmap.site/) at: <link>

```[tasklist]
### Tasks
- [ ] Ban the nodes on the network
- [ ] Start my own node
- [ ] profit
```
